name: CI
run-name: '🤖 [CI] ${{ github.event.head_commit.message }} (${{ github.ref }})'

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: ' 🤖 CI'
    runs-on: 'ubuntu-latest'

    steps:
      - name: '🚚 Checkout branch'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: '📦 Cache moon artifacts'
        uses: actions/cache@v4
        with:
          path: .moon/cache
          key: ${{ runner.os }}-moon-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-moon-

      - name: '📦 Cache bun artifacts'
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}

      - name: '🌑 Setup moonrepo'
        uses: 'moonrepo/setup-toolchain@v0'

      - name: '🌗 Moonrepo CI'
        run: 'moon ci --color'

      - name: '🌕 Moonrepo CI Retrospect'
        uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()
